export const AGREEMENT_TYPE_SELECTED_BOTH = 'AGREEMENT_TYPE_SELECTED_BOTH'
export const AGREEMENT_TYPE_SELECTED_OUTGOING = 'AGREEMENT_TYPE_SELECTED_OUTGOING'
export const AGREEMENT_TYPE_SELECTED_INCOMING = 'AGREEMENT_TYPE_SELECTED_INCOMING'

export const SUMMARY_ROW_CLIENT = 'SUMMARY_ROW_CLIENT'
export const SUMMARY_ROW_CPTY = 'SUMMARY_ROW_CPTY'
export const SUMMARY_ROW_CPTY_DETAIL = 'SUMMARY_ROW_CPTY_DETAIL'