export const DASHBOARD_URL = 'http://margin.acuo.com/acuo/api/margin/dashboard'
export const RECON_URL = 'http://margin.acuo.com/acuo/api/margin/items/all/999'
export const RECON_DATA_URL = 'http://margin.acuo.com/acuo/api/margin/reconcile/'
export const ALLOCATE_COLLATERALS_URL = 'http://52.74.186.112:8081/allocate-selection'
export const OPTIMISATION_URL = 'http://52.74.186.112:8081/optimisation'
export const MARGIN_SELECTION_URL = 'http://52.74.186.112:8081/init-selection'
export const COLLATERAL_URL = 'http://52.74.186.112:8081/init-collateral'
export const UPLOAD_FILE_URL = 'http://valuation.acuo.com/acuo/api/upload'