export const COLLATERAL_EARMARKED = "earmarked"
export const POPUP_TAB_ALLOCATE = "allocate"
export const POPUP_TAB_AMEND = "amend"
export const POPUP_TAB_EARMARK = "earmark"
export const POPUP_TAB_REMOVE_EARMARK = "remove"