export const FLIGHT_TIME = "Time"
export const FLIGHT_ASSET = "Asset"
export const FLIGHT_AGREEMENT = "Agreement"
export const FLIGHT_FROM = "From"
export const FLIGHT_TO = "To"
export const FLIGHT_VALUE = "Value"
export const FLIGHT_CCY = "CCY"
export const FLIGHT_STATUS = "Status"